api_platform:
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  formats:
    jsonld: ["application/ld+json"]
    json: ["application/json"]
    xml: ["application/xml", "text/xml"]
    html: ["text/html"]
    multipart: ["multipart/form-data"]
  patch_formats:
    json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
  show_webby: false
  defaults:
    pagination_items_per_page: 10
  eager_loading:
    max_joins: 100
