<?php

namespace ContainerAGRoH5u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvailablityRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\AvailablityRepository' shared autowired service.
     *
     * @return \App\Repository\AvailablityRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AvailablityRepository'] = new \App\Repository\AvailablityRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
