<?php

namespace ContainerAGRoH5u;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMeControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MeController' shared autowired service.
     *
     * @return \App\Controller\MeController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MeController'] = $instance = new \App\Controller\MeController(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));

        $instance->setContainer(($container->privates['.service_locator.l1ae.Qz'] ?? $container->load('get_ServiceLocator_L1ae_QzService'))->withContext('App\\Controller\\MeController', $container));

        return $instance;
    }
}
