<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOoTy2Kg\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOoTy2Kg/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerOoTy2Kg.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerOoTy2Kg\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerOoTy2Kg\App_KernelProdDebugContainer([
    'container.build_hash' => 'OoTy2Kg',
    'container.build_id' => '312a63c2',
    'container.build_time' => 1659012203,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOoTy2Kg');
