<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAGRoH5u\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAGRoH5u/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerAGRoH5u.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerAGRoH5u\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerAGRoH5u\App_KernelProdContainer([
    'container.build_hash' => 'AGRoH5u',
    'container.build_id' => '2287b1bb',
    'container.build_time' => 1659007031,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAGRoH5u');
