<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSUPxHuX\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSUPxHuX/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerSUPxHuX.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerSUPxHuX\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerSUPxHuX\App_KernelTestDebugContainer([
    'container.build_hash' => 'SUPxHuX',
    'container.build_id' => '01ed8063',
    'container.build_time' => 1658184090,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSUPxHuX');
